default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  ports: 5432
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: Mapen_development


test:
  <<: *default
  database: Mapen_test
